// This is an autogenerated file. DO NOT MODIFY
package queries

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type CreateQueryInput struct {
	Language   string  `validate:"required" form:"Language"`
	Query      string  `validate:"required" form:"Query"`
	Tasks      *string `form:"Tasks,omitempty"`
	ModelBuild *string `form:"ModelBuild,omitempty"`
}

type CreateQueryResponseField struct {
	Name  string `json:"name"`
	Value string `json:"value"`
	Type  string `json:"type"`
}

type CreateQueryResponseResult struct {
	Task   string                     `json:"task"`
	Fields []CreateQueryResponseField `json:"fields"`
}

type CreateQueryResponse struct {
	Sid           string                    `json:"sid"`
	AccountSid    string                    `json:"account_sid"`
	AssistantSid  string                    `json:"assistant_sid"`
	ModelBuildSid string                    `json:"model_build_sid"`
	SampleSid     string                    `json:"sample_sid"`
	Status        string                    `json:"status"`
	Language      string                    `json:"language"`
	Query         string                    `json:"query"`
	Results       CreateQueryResponseResult `json:"results"`
	SourceChannel string                    `json:"source_channel"`
	DialogueSid   *string                   `json:"dialogue_sid,omitempty"`
	DateCreated   time.Time                 `json:"date_created"`
	DateUpdated   *time.Time                `json:"date_updated,omitempty"`
	URL           string                    `json:"url"`
}

func (c Client) Create(input *CreateQueryInput) (*CreateQueryResponse, error) {
	return c.CreateWithContext(context.Background(), input)
}

func (c Client) CreateWithContext(context context.Context, input *CreateQueryInput) (*CreateQueryResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Assistants/{assistantSid}/Queries",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"assistantSid": c.assistantSid,
		},
	}

	response := &CreateQueryResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
