// This is an autogenerated file. DO NOT MODIFY
package web_channel

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type UpdateWebChannelInput struct {
	ChatStatus        *string `form:"ChatStatus,omitempty"`
	PreEngagementData *string `form:"PreEngagementData,omitempty"`
}

type UpdateWebChannelResponse struct {
	AccountSid  string     `json:"account_sid"`
	DateCreated time.Time  `json:"date_created"`
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	FlexFlowSid string     `json:"flex_flow_sid"`
	Sid         string     `json:"sid"`
	URL         string     `json:"url"`
}

func (c Client) Update(input *UpdateWebChannelInput) (*UpdateWebChannelResponse, error) {
	return c.UpdateWithContext(context.Background(), input)
}

func (c Client) UpdateWithContext(context context.Context, input *UpdateWebChannelInput) (*UpdateWebChannelResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/WebChannels/{sid}",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"sid": c.sid,
		},
	}

	response := &UpdateWebChannelResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
