// This is an autogenerated file. DO NOT MODIFY
package fax

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetFaxResponse struct {
	Sid         string     `json:"sid"`
	AccountSid  string     `json:"account_sid"`
	APIVersion  string     `json:"api_version"`
	Direction   string     `json:"direction"`
	From        string     `json:"from"`
	To          string     `json:"to"`
	Quality     string     `json:"quality"`
	Status      string     `json:"status"`
	MediaURL    *string    `json:"media_url,omitempty"`
	MediaSid    *string    `json:"media_sid,omitempty"`
	Duration    *int       `json:"duration,omitempty"`
	NumPages    *int       `json:"num_pages,omitempty"`
	Price       *string    `json:"price,omitempty"`
	PriceUnit   *string    `json:"price_unit,omitempty"`
	DateCreated time.Time  `json:"date_created"`
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	URL         string     `json:"url"`
}

func (c Client) Get() (*GetFaxResponse, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetFaxResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Faxes/{sid}",
		PathParams: map[string]string{
			"sid": c.sid,
		},
	}

	response := &GetFaxResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
