// This is an autogenerated file. DO NOT MODIFY
package webhook

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type FetchChannelWebhookResponseConfiguration struct {
	Filters    *[]string `json:"filters,omitempty"`
	FlowSid    *string   `json:"flow_sid,omitempty"`
	Method     *string   `json:"method,omitempty"`
	RetryCount *int      `json:"retry_count,omitempty"`
	Triggers   *[]string `json:"triggers,omitempty"`
	URL        *string   `json:"url,omitempty"`
}

type FetchChannelWebhookResponse struct {
	AccountSid    string                                   `json:"account_sid"`
	ChannelSid    string                                   `json:"channel_sid"`
	Configuration FetchChannelWebhookResponseConfiguration `json:"configuration"`
	DateCreated   time.Time                                `json:"date_created"`
	DateUpdated   *time.Time                               `json:"date_updated,omitempty"`
	ServiceSid    string                                   `json:"service_sid"`
	Sid           string                                   `json:"sid"`
	Type          string                                   `json:"type"`
	URL           string                                   `json:"url"`
}

func (c Client) Fetch() (*FetchChannelWebhookResponse, error) {
	return c.FetchWithContext(context.Background())
}

func (c Client) FetchWithContext(context context.Context) (*FetchChannelWebhookResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Services/{serviceSid}/Channels/{channelSid}/Webhooks/{sid}",
		PathParams: map[string]string{
			"serviceSid": c.serviceSid,
			"channelSid": c.channelSid,
			"sid":        c.sid,
		},
	}

	response := &FetchChannelWebhookResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
