// This is an autogenerated file. DO NOT MODIFY
package webhook

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetChannelWebhookOutputConfiguration struct {
	Url        *string   `json:"Url,omitempty"`
	Method     *string   `json:"method,omitempty"`
	Filters    *[]string `json:"filters,omitempty"`
	Triggers   *[]string `json:"triggers,omitempty"`
	FlowSid    *string   `json:"flow_sid,omitempty"`
	RetryCount *int      `json:"retry_count,omitempty"`
}

type GetChannelWebhookOutput struct {
	Sid           string                               `json:"sid"`
	AccountSid    string                               `json:"account_sid"`
	ServiceSid    string                               `json:"service_sid"`
	ChannelSid    string                               `json:"channel_sid"`
	Configuration GetChannelWebhookOutputConfiguration `json:"configuration"`
	DateCreated   time.Time                            `json:"date_created"`
	DateUpdated   *time.Time                           `json:"date_updated,omitempty"`
	URL           string                               `json:"url"`
}

func (c Client) Get() (*GetChannelWebhookOutput, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetChannelWebhookOutput, error) {
	op := client.Operation{
		HTTPMethod: http.MethodGet,
		HTTPPath:   "/Services/{serviceSid}/Channels/{channelSid}/Webhooks/{sid}",
		PathParams: map[string]string{
			"serviceSid": c.serviceSid,
			"channelSid": c.channelSid,
			"sid":        c.sid,
		},
	}

	output := &GetChannelWebhookOutput{}
	if err := c.client.Send(context, op, nil, output); err != nil {
		return nil, err
	}
	return output, nil
}
