// This is an autogenerated file. DO NOT MODIFY
package messages

import "github.com/RJPearson94/twilio-sdk-go/client"

type Client struct {
	client *client.Client

	accountSid string
}

type ClientProperties struct {
	AccountSid string
}

func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		accountSid: properties.AccountSid,
	}
}
