// This is an autogenerated file. DO NOT MODIFY
package activity

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type UpdateActivityInput struct {
	FriendlyName *string `form:"FriendlyName,omitempty"`
}

type UpdateActivityResponse struct {
	Sid          string     `json:"sid"`
	AccountSid   string     `json:"account_sid"`
	WorkspaceSid string     `json:"workspace_sid"`
	FriendlyName string     `json:"friendly_name"`
	Available    bool       `json:"available"`
	DateCreated  time.Time  `json:"date_created"`
	DateUpdated  *time.Time `json:"date_updated,omitempty"`
	URL          string     `json:"url"`
}

func (c Client) Update(input *UpdateActivityInput) (*UpdateActivityResponse, error) {
	return c.UpdateWithContext(context.Background(), input)
}

func (c Client) UpdateWithContext(context context.Context, input *UpdateActivityInput) (*UpdateActivityResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Workspaces/{workspaceSid}/Activities/{sid}",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"workspaceSid": c.workspaceSid,
			"sid":          c.sid,
		},
	}

	response := &UpdateActivityResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
