// This is an autogenerated file. DO NOT MODIFY
package item

import "github.com/RJPearson94/twilio-sdk-go/client"

type Client struct {
	client *client.Client

	index       int
	serviceSid  string
	syncListSid string
}

// The properties required to manage the item resources
type ClientProperties struct {
	Index       int
	ServiceSid  string
	SyncListSid string
}

// Create a new instance of the client
func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		index:       properties.Index,
		serviceSid:  properties.ServiceSid,
		syncListSid: properties.SyncListSid,
	}
}
