// This is an autogenerated file. DO NOT MODIFY
package variable

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type UpdateVariableInput struct {
	Key   *string `form:"Key,omitempty"`
	Value *string `form:"Value,omitempty"`
}

type UpdateVariableOutput struct {
	Sid            string     `json:"sid"`
	AccountSid     string     `json:"account_sid"`
	ServiceSid     string     `json:"service_sid"`
	EnvironmentSid string     `json:"environment_sid"`
	Key            string     `json:"key"`
	Value          string     `json:"value"`
	DateCreated    time.Time  `json:"date_created"`
	DateUpdated    *time.Time `json:"date_updated,omitempty"`
	URL            string     `json:"url"`
}

func (c Client) Update(input *UpdateVariableInput) (*UpdateVariableOutput, error) {
	return c.UpdateWithContext(context.Background(), input)
}

func (c Client) UpdateWithContext(context context.Context, input *UpdateVariableInput) (*UpdateVariableOutput, error) {
	op := client.Operation{
		HTTPMethod:  http.MethodPost,
		HTTPPath:    "/Services/{serviceSid}/Environments/{environmentSid}/Variables/{sid}",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"serviceSid":     c.serviceSid,
			"environmentSid": c.environmentSid,
			"sid":            c.sid,
		},
	}

	output := &UpdateVariableOutput{}
	if err := c.client.Send(context, op, input, output); err != nil {
		return nil, err
	}
	return output, nil
}
