// This is an autogenerated file. DO NOT MODIFY
package document

import (
	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/service/sync/v1/service/document/permissions"
)

type Client struct {
	client *client.Client

	serviceSid string
	sid        string

	// Sub client to manage permissions resources
	Permissions func(string) *permissions.Client
}

// The properties required to manage the document resources
type ClientProperties struct {
	ServiceSid string
	Sid        string
}

// Create a new instance of the client
func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		serviceSid: properties.ServiceSid,
		sid:        properties.Sid,

		Permissions: func(identity string) *permissions.Client {
			return permissions.New(client, permissions.ClientProperties{
				DocumentSid: properties.Sid,
				Identity:    identity,
				ServiceSid:  properties.ServiceSid,
			})
		},
	}
}
