// This is an autogenerated file. DO NOT MODIFY
package flow

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type UpdateFlowInput struct {
	FriendlyName  string `form:"FriendlyName,omitempty"`
	Status        string `validate:"required" form:"Status"`
	Definition    string `form:"Definition,omitempty"`
	CommitMessage string `form:"CommitMessage,omitempty"`
}

type UpdateFlowOutput struct {
	Sid           string         `json:"sid"`
	AccountSid    string         `json:"account_sid"`
	FriendlyName  string         `json:"friendly_name"`
	Definition    interface{}    `json:"definition"`
	Status        string         `json:"status"`
	Revision      int            `json:"revision"`
	CommitMessage *string        `json:"commit_message,omitempty"`
	Valid         bool           `json:"valid"`
	Errors        *[]interface{} `json:"errors,omitempty"`
	Warnings      *[]interface{} `json:"warnings,omitempty"`
	DateCreated   time.Time      `json:"date_created"`
	DateUpdated   *time.Time     `json:"date_updated,omitempty"`
	WebhookURL    string         `json:"webhook_url"`
	URL           string         `json:"url"`
}

func (c Client) Update(input *UpdateFlowInput) (*UpdateFlowOutput, error) {
	return c.UpdateWithContext(context.Background(), input)
}

func (c Client) UpdateWithContext(context context.Context, input *UpdateFlowInput) (*UpdateFlowOutput, error) {
	op := client.Operation{
		HTTPMethod:  http.MethodPost,
		HTTPPath:    "/Flows/{sid}",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"sid": c.sid,
		},
	}

	output := &UpdateFlowOutput{}
	if err := c.client.Send(context, op, input, output); err != nil {
		return nil, err
	}
	return output, nil
}
