// This is an autogenerated file. DO NOT MODIFY
package worker

import (
	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/service/taskrouter/v1/workspace/worker/channel"
	"github.com/RJPearson94/twilio-sdk-go/service/taskrouter/v1/workspace/worker/channels"
)

// Client for managing a specific worker resource
// See https://www.twilio.com/docs/taskrouter/api/worker for more details
type Client struct {
	client *client.Client

	sid          string
	workspaceSid string

	Channel  func(string) *channel.Client
	Channels *channels.Client
}

// ClientProperties are the properties required to manage the worker resources
type ClientProperties struct {
	Sid          string
	WorkspaceSid string
}

// New creates a new instance of the worker client
func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		sid:          properties.Sid,
		workspaceSid: properties.WorkspaceSid,

		Channel: func(channelSid string) *channel.Client {
			return channel.New(client, channel.ClientProperties{
				Sid:          channelSid,
				WorkerSid:    properties.Sid,
				WorkspaceSid: properties.WorkspaceSid,
			})
		},
		Channels: channels.New(client, channels.ClientProperties{
			WorkerSid:    properties.Sid,
			WorkspaceSid: properties.WorkspaceSid,
		}),
	}
}
