// This is an autogenerated file. DO NOT MODIFY
package worker

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type UpdateWorkerInput struct {
	FriendlyName              *string `form:"FriendlyName,omitempty"`
	ActivitySid               *string `form:"ActivitySid,omitempty"`
	Attributes                *string `form:"Attributes,omitempty"`
	RejectPendingReservations *bool   `form:"RejectPendingReservations,omitempty"`
}

type UpdateWorkflowOutput struct {
	Sid               string      `json:"sid"`
	AccountSid        string      `json:"account_sid"`
	WorkspaceSid      string      `json:"workspace_sid"`
	ActivitySid       string      `json:"activity_sid"`
	FriendlyName      string      `json:"friendly_name"`
	ActivityName      string      `json:"activity_name"`
	Attributes        interface{} `json:"attributes"`
	Available         bool        `json:"available"`
	DateCreated       time.Time   `json:"date_created"`
	DateUpdated       *time.Time  `json:"date_updated,omitempty"`
	DateStatusChanged *time.Time  `json:"date_status_changed,omitempty"`
	URL               string      `json:"url"`
}

func (c Client) Update(input *UpdateWorkerInput) (*UpdateWorkflowOutput, error) {
	return c.UpdateWithContext(context.Background(), input)
}

func (c Client) UpdateWithContext(context context.Context, input *UpdateWorkerInput) (*UpdateWorkflowOutput, error) {
	op := client.Operation{
		HTTPMethod:  http.MethodPost,
		HTTPPath:    "/Workspaces/{workspaceSid}/Workers/{sid}",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"workspaceSid": c.workspaceSid,
			"sid":          c.sid,
		},
	}

	output := &UpdateWorkflowOutput{}
	if err := c.client.Send(context, op, input, output); err != nil {
		return nil, err
	}
	return output, nil
}
