// This is an autogenerated file. DO NOT MODIFY
package revision

import (
	"context"
	"net/http"
	"strconv"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type FetchRevisionResponse struct {
	AccountSid    string         `json:"account_sid"`
	CommitMessage *string        `json:"commit_message,omitempty"`
	DateCreated   time.Time      `json:"date_created"`
	DateUpdated   *time.Time     `json:"date_updated,omitempty"`
	Definition    interface{}    `json:"definition"`
	Errors        *[]interface{} `json:"errors,omitempty"`
	FriendlyName  string         `json:"friendly_name"`
	Revision      int            `json:"revision"`
	Sid           string         `json:"sid"`
	Status        string         `json:"status"`
	URL           string         `json:"url"`
	Valid         bool           `json:"valid"`
	Warnings      *[]interface{} `json:"warnings,omitempty"`
	WebhookURL    string         `json:"webhook_url"`
}

func (c Client) Fetch() (*FetchRevisionResponse, error) {
	return c.FetchWithContext(context.Background())
}

func (c Client) FetchWithContext(context context.Context) (*FetchRevisionResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Flows/{flowSid}/Revisions/{revisionNumber}",
		PathParams: map[string]string{
			"flowSid":        c.flowSid,
			"revisionNumber": strconv.Itoa(c.revisionNumber),
		},
	}

	response := &FetchRevisionResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
