// This is an autogenerated file. DO NOT MODIFY
package variables

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type CreateVariableInput struct {
	Key   string `validate:"required" form:"Key"`
	Value string `validate:"required" form:"Value"`
}

type CreateVariableOutput struct {
	Sid            string     `json:"sid"`
	AccountSid     string     `json:"account_sid"`
	ServiceSid     string     `json:"service_sid"`
	EnvironmentSid string     `json:"environment_sid"`
	Key            string     `json:"key"`
	Value          string     `json:"value"`
	DateCreated    time.Time  `json:"date_created"`
	DateUpdated    *time.Time `json:"date_updated,omitempty"`
	URL            string     `json:"url"`
}

func (c Client) Create(input *CreateVariableInput) (*CreateVariableOutput, error) {
	return c.CreateWithContext(context.Background(), input)
}

func (c Client) CreateWithContext(context context.Context, input *CreateVariableInput) (*CreateVariableOutput, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Services/{serviceSid}/Environments/{environmentSid}/Variables",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"serviceSid":     c.serviceSid,
			"environmentSid": c.environmentSid,
		},
	}

	output := &CreateVariableOutput{}
	if err := c.client.Send(context, op, input, output); err != nil {
		return nil, err
	}
	return output, nil
}
