// This is an autogenerated file. DO NOT MODIFY
package invite

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetChannelInviteResponse struct {
	Sid         string     `json:"sid"`
	AccountSid  string     `json:"account_sid"`
	ServiceSid  string     `json:"service_sid"`
	ChannelSid  string     `json:"channel_sid"`
	RoleSid     *string    `json:"role_sid,omitempty"`
	CreatedBy   *string    `json:"created_by,omitempty"`
	Identity    string     `json:"identity"`
	DateCreated time.Time  `json:"date_created"`
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	URL         string     `json:"url"`
}

func (c Client) Get() (*GetChannelInviteResponse, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetChannelInviteResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Services/{serviceSid}/Channels/{channelSid}/Invites/{sid}",
		PathParams: map[string]string{
			"serviceSid": c.serviceSid,
			"channelSid": c.channelSid,
			"sid":        c.sid,
		},
	}

	response := &GetChannelInviteResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
