// This is an autogenerated file. DO NOT MODIFY
package permissions

import (
	"context"
	"net/http"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type UpdateListPermissionsInput struct {
	Manage bool `form:"Manage"`
	Read   bool `form:"Read"`
	Write  bool `form:"Write"`
}

type UpdateListPermissionsResponse struct {
	AccountSid string `json:"account_sid"`
	Identity   string `json:"identity"`
	ListSid    string `json:"list_sid"`
	Manage     bool   `json:"manage"`
	Read       bool   `json:"read"`
	ServiceSid string `json:"service_sid"`
	URL        string `json:"url"`
	Write      bool   `json:"write"`
}

func (c Client) Update(input *UpdateListPermissionsInput) (*UpdateListPermissionsResponse, error) {
	return c.UpdateWithContext(context.Background(), input)
}

func (c Client) UpdateWithContext(context context.Context, input *UpdateListPermissionsInput) (*UpdateListPermissionsResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Services/{serviceSid}/Lists/{listSid}/Permissions/{identity}",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"serviceSid": c.serviceSid,
			"listSid":    c.listSid,
			"identity":   c.identity,
		},
	}

	response := &UpdateListPermissionsResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
