// This is an autogenerated file. DO NOT MODIFY
package task_channels

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type CreateTaskChannelInput struct {
	FriendlyName            string `validate:"required" form:"FriendlyName"`
	UniqueName              string `validate:"required" form:"UniqueName"`
	ChannelOptimizedRouting *bool  `form:"ChannelOptimizedRouting,omitempty"`
}

type CreateTaskChannelResponse struct {
	Sid                     string     `json:"sid"`
	AccountSid              string     `json:"account_sid"`
	WorkspaceSid            string     `json:"workspace_sid"`
	FriendlyName            string     `json:"friendly_name"`
	UniqueName              string     `json:"unique_name"`
	ChannelOptimizedRouting *bool      `json:"channel_optimized_routing,omitempty"`
	DateCreated             time.Time  `json:"date_created"`
	DateUpdated             *time.Time `json:"date_updated,omitempty"`
	URL                     string     `json:"url"`
}

func (c Client) Create(input *CreateTaskChannelInput) (*CreateTaskChannelResponse, error) {
	return c.CreateWithContext(context.Background(), input)
}

func (c Client) CreateWithContext(context context.Context, input *CreateTaskChannelInput) (*CreateTaskChannelResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Workspaces/{workspaceSid}/TaskChannels",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"workspaceSid": c.workspaceSid,
		},
	}

	response := &CreateTaskChannelResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
