// This is an autogenerated file. DO NOT MODIFY
package assistant

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetAssistantResponse struct {
	Sid                 string     `json:"sid"`
	AccountSid          string     `json:"account_sid"`
	LatestModelBuildSid *string    `json:"latest_model_build_sid,omitempty"`
	UniqueName          string     `json:"unique_name"`
	FriendlyName        *string    `json:"friendly_name,omitempty"`
	CallbackEvents      *string    `json:"callback_events,omitempty"`
	CallbackURL         *string    `json:"callback_url,omitempty"`
	LogQueries          bool       `json:"log_queries"`
	DevelopmentStage    string     `json:"development_stage"`
	NeedsModelBuild     *bool      `json:"needs_model_build,omitempty"`
	DateCreated         time.Time  `json:"date_created"`
	DateUpdated         *time.Time `json:"date_updated,omitempty"`
	URL                 string     `json:"url"`
}

func (c Client) Get() (*GetAssistantResponse, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetAssistantResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Assistants/{sid}",
		PathParams: map[string]string{
			"sid": c.sid,
		},
	}

	response := &GetAssistantResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
