// This is an autogenerated file. DO NOT MODIFY
package configuration

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type UpdateConfigurationInputTaskQueue struct {
	Sid         string `validate:"required" json:"sid"`
	Targettable bool   `validate:"required" json:"targettable"`
}

type UpdateConfigurationInputSkill struct {
	Name       string `validate:"required" json:"name"`
	MultiValue bool   `validate:"required" json:"multivalue"`
	Minimum    int    `validate:"required" json:"minimum"`
	Maximum    bool   `validate:"required" json:"maximum"`
}

type UpdateConfigurationInputWorkerChannel struct {
	Name         string `validate:"required" json:"name"`
	Availability bool   `validate:"required" json:"availability"`
	Capacity     int    `validate:"required" json:"capacity"`
}

type UpdateConfigurationInputIntegration struct {
	Name   string  `validate:"required" json:"name"`
	Type   string  `validate:"required" json:"type"`
	Active bool    `validate:"required" json:"active"`
	Config string  `validate:"required" json:"config"`
	Logo   *string `json:"logo,omitempty"`
	Author *string `json:"author,omitempty"`
}

type UpdateConfigurationInput struct {
	AccountSid                   string                                              `validate:"required" json:"account_sid"`
	ChatServiceInstanceSid       *string                                             `json:"chat_service_instance_sid,omitempty"`
	MessagingServiceInstanceSid  *string                                             `json:"messaging_service_instance_sid,omitempty"`
	CrmEnabled                   *bool                                               `json:"crm_type,omitempty"`
	CrmType                      *string                                             `json:"crm_type,omitempty"`
	CrmCallbackURL               *string                                             `json:"crm_callback_url,omitempty"`
	CrmFallbackURL               *string                                             `json:"crm_fallback_url,omitempty"`
	CrmAttributes                *interface{}                                        `json:"crm_attributes,omitempty"`
	UiLanguage                   *string                                             `json:"ui_language,omitempty"`
	UiAttributes                 *interface{}                                        `json:"ui_attributes,omitempty"`
	UiDependencies               *interface{}                                        `json:"ui_dependencies,omitempty"`
	UiVersion                    *string                                             `json:"ui_version,omitempty"`
	TaskRouterTargetWorkflowSid  *string                                             `json:"taskrouter_target_workflow_sid,omitempty"`
	TaskRouterTargetTaskQueueSid *string                                             `json:"taskrouter_target_taskqueue_sid,omitempty"`
	TaskRouterTaskQueues         *[]UpdateConfigurationInputTaskQueue                `json:"taskrouter_taskqueues,omitempty"`
	TaskRouterSkills             *[]UpdateConfigurationInputSkill                    `json:"taskrouter_skills,omitempty"`
	TaskRouterWorkerChannels     *map[string][]UpdateConfigurationInputWorkerChannel `json:"taskrouter_worker_channels,omitempty"`
	TaskRouterWorkerAttributes   *map[string]interface{}                             `json:"taskrouter_worker_attributes,omitempty"`
	CallRecordingEnabled         *bool                                               `json:"call_recording_enabled,omitempty"`
	CallRecordingWebhookURL      *string                                             `json:"call_recording_webhook_url,omitempty"`
	PublicAttributes             *interface{}                                        `json:"public_attributes,omitempty"`
	Attributes                   *interface{}                                        `json:"attributes,omitempty"`
	PluginServiceEnabled         *bool                                               `json:"plugin_service_enabled,omitempty"`
	PluginServiceAttributes      *interface{}                                        `json:"plugin_service_attributes,omitempty"`
	Integrations                 *[]UpdateConfigurationInputIntegration              `json:"integrations,omitempty"`
	WfmIntegrations              *[]UpdateConfigurationInputIntegration              `json:"wfm_integrations,omitempty"`
	OutboundCallFlows            *interface{}                                        `json:"outbound_call_flows,omitempty"`
	QueueStatsConfiguration      *interface{}                                        `json:"queue_stats_configuration,omitempty"`
	ServerlessServiceSids        *[]string                                           `json:"serverless_service_sids,omitempty"`
}

type UpdateConfigurationOutputTaskQueue struct {
	Sid         string `json:"sid"`
	Targettable bool   `json:"targettable"`
}

type UpdateConfigurationOutputSkill struct {
	Name       string `json:"name"`
	MultiValue bool   `json:"multivalue"`
	Minimum    int    `json:"minimum"`
	Maximum    bool   `json:"maximum"`
}

type UpdateConfigurationOutputWorkerChannel struct {
	Name         string `json:"name"`
	Availability bool   `json:"availability"`
	Capacity     int    `json:"capacity"`
}

type UpdateConfigurationOutputIntegration struct {
	Name   string  `json:"name"`
	Type   string  `json:"type"`
	Active bool    `json:"active"`
	Config string  `json:"config"`
	Logo   *string `json:"logo,omitempty"`
	Author *string `json:"author,omitempty"`
}

type UpdateConfigurationOutput struct {
	AccountSid                   string                                               `json:"account_sid"`
	FlexServiceInstanceSid       string                                               `json:"flex_service_instance_sid"`
	ChatServiceInstanceSid       *string                                              `json:"chat_service_instance_sid,omitempty"`
	MessagingServiceInstanceSid  *string                                              `json:"messaging_service_instance_sid,omitempty"`
	CrmEnabled                   *bool                                                `json:"crm_type,omitempty"`
	CrmType                      *string                                              `json:"crm_type,omitempty"`
	CrmCallbackURL               *string                                              `json:"crm_callback_url,omitempty"`
	CrmFallbackURL               *string                                              `json:"crm_fallback_url,omitempty"`
	CrmAttributes                *interface{}                                         `json:"crm_attributes,omitempty"`
	UiLanguage                   *string                                              `json:"ui_language,omitempty"`
	UiAttributes                 *interface{}                                         `json:"ui_attributes,omitempty"`
	UiDependencies               *interface{}                                         `json:"ui_dependencies,omitempty"`
	UiVersion                    string                                               `json:"ui_version"`
	TaskRouterWorkspaceSid       string                                               `json:"taskrouter_workspace_sid"`
	TaskRouterTargetWorkflowSid  string                                               `json:"taskrouter_target_workflow_sid"`
	TaskRouterTargetTaskQueueSid string                                               `json:"taskrouter_target_taskqueue_sid"`
	TaskRouterTaskQueues         *[]UpdateConfigurationOutputTaskQueue                `json:"taskrouter_taskqueues,omitempty"`
	TaskRouterSkills             *[]UpdateConfigurationOutputSkill                    `json:"taskrouter_skills,omitempty"`
	TaskRouterWorkerChannels     *map[string][]UpdateConfigurationOutputWorkerChannel `json:"taskrouter_worker_channels,omitempty"`
	TaskRouterWorkerAttributes   *map[string]interface{}                              `json:"taskrouter_worker_attributes,omitempty"`
	TaskRouterOfflineActivitySid string                                               `json:"taskrouter_offline_activity_sid"`
	CallRecordingEnabled         *bool                                                `json:"call_recording_enabled,omitempty"`
	CallRecordingWebhookURL      *string                                              `json:"call_recording_webhook_url,omitempty"`
	PublicAttributes             *interface{}                                         `json:"public_attributes,omitempty"`
	Attributes                   *interface{}                                         `json:"attributes,omitempty"`
	Status                       string                                               `json:"status"`
	RuntimeDomain                string                                               `json:"runtime_domain"`
	ServiceVersion               *string                                              `json:"service_version,omitempty"`
	PluginServiceEnabled         *bool                                                `json:"plugin_service_enabled,omitempty"`
	PluginServiceAttributes      *interface{}                                         `json:"plugin_service_attributes,omitempty"`
	Integrations                 *[]UpdateConfigurationOutputIntegration              `json:"integrations,omitempty"`
	WfmIntegrations              *[]UpdateConfigurationOutputIntegration              `json:"wfm_integrations,omitempty"`
	OutboundCallFlows            *interface{}                                         `json:"outbound_call_flows,omitempty"`
	QueueStatsConfiguration      *interface{}                                         `json:"queue_stats_configuration,omitempty"`
	ServerlessServiceSids        *[]string                                            `json:"serverless_service_sids,omitempty"`
	DateCreated                  time.Time                                            `json:"date_created"`
	DateUpdated                  *time.Time                                           `json:"date_updated,omitempty"`
	URL                          string                                               `json:"url"`
}

func (c Client) Update(input *UpdateConfigurationInput) (*UpdateConfigurationOutput, error) {
	return c.UpdateWithContext(context.Background(), input)
}

func (c Client) UpdateWithContext(context context.Context, input *UpdateConfigurationInput) (*UpdateConfigurationOutput, error) {
	op := client.Operation{
		HTTPMethod:  http.MethodPost,
		HTTPPath:    "/Configuration",
		ContentType: client.JSON,
	}

	output := &UpdateConfigurationOutput{}
	if err := c.client.Send(context, op, input, output); err != nil {
		return nil, err
	}
	return output, nil
}
