// This is an autogenerated file. DO NOT MODIFY
package service

import (
	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/service/sync/v1/service/document"
	"github.com/RJPearson94/twilio-sdk-go/service/sync/v1/service/documents"
	"github.com/RJPearson94/twilio-sdk-go/service/sync/v1/service/list"
	"github.com/RJPearson94/twilio-sdk-go/service/sync/v1/service/lists"
)

type Client struct {
	client *client.Client

	sid string

	Document  func(string) *document.Client
	Documents *documents.Client
	List      func(string) *list.Client
	Lists     *lists.Client
}

type ClientProperties struct {
	Sid string
}

func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		sid: properties.Sid,

		Document: func(documentSid string) *document.Client {
			return document.New(client, document.ClientProperties{
				ServiceSid: properties.Sid,
				Sid:        documentSid,
			})
		},
		Documents: documents.New(client, documents.ClientProperties{
			ServiceSid: properties.Sid,
		}),
		List: func(listSid string) *list.Client {
			return list.New(client, list.ClientProperties{
				ServiceSid: properties.Sid,
				Sid:        listSid,
			})
		},
		Lists: lists.New(client, lists.ClientProperties{
			ServiceSid: properties.Sid,
		}),
	}
}
