// This is an autogenerated file. DO NOT MODIFY
package field_value

import "github.com/RJPearson94/twilio-sdk-go/client"

type Client struct {
	client *client.Client

	sid          string
	assistantSid string
	fieldTypeSid string
}

type ClientProperties struct {
	Sid          string
	AssistantSid string
	FieldTypeSid string
}

func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		sid:          properties.Sid,
		assistantSid: properties.AssistantSid,
		fieldTypeSid: properties.FieldTypeSid,
	}
}
