// This is an autogenerated file. DO NOT MODIFY
package service

import (
	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/service/messaging/v1/service/phone_number"
	"github.com/RJPearson94/twilio-sdk-go/service/messaging/v1/service/phone_numbers"
)

type Client struct {
	client *client.Client

	sid string

	PhoneNumber  func(string) *phone_number.Client
	PhoneNumbers *phone_numbers.Client
}

type ClientProperties struct {
	Sid string
}

func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		sid: properties.Sid,

		PhoneNumber: func(phoneNumberSid string) *phone_number.Client {
			return phone_number.New(client, phone_number.ClientProperties{
				ServiceSid: properties.Sid,
				Sid:        phoneNumberSid,
			})
		},
		PhoneNumbers: phone_numbers.New(client, phone_numbers.ClientProperties{
			ServiceSid: properties.Sid,
		}),
	}
}
