// This is an autogenerated file. DO NOT MODIFY
package test_users

import (
	"context"
	"net/http"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type UpdateTestUsersInput struct {
	TestUsers []string `validate:"required" mapstructure:"TestUsers"`
}

type UpdateTestUsersOutput struct {
	Sid       string   `json:"sid"`
	TestUsers []string `json:"test_users"`
	URL       string   `json:"url"`
}

func (c Client) Update(input *UpdateTestUsersInput) (*UpdateTestUsersOutput, error) {
	return c.UpdateWithContext(context.Background(), input)
}

func (c Client) UpdateWithContext(context context.Context, input *UpdateTestUsersInput) (*UpdateTestUsersOutput, error) {
	op := client.Operation{
		HTTPMethod:  http.MethodPost,
		HTTPPath:    "/Flows/{flowSid}/TestUsers",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"flowSid": c.flowSid,
		},
	}

	output := &UpdateTestUsersOutput{}
	if err := c.client.Send(context, op, input, output); err != nil {
		return nil, err
	}
	return output, nil
}
