// This is an autogenerated file. DO NOT MODIFY
package item

import "github.com/RJPearson94/twilio-sdk-go/client"

type Client struct {
	client *client.Client

	key        string
	serviceSid string
	syncMapSid string
}

type ClientProperties struct {
	Key        string
	ServiceSid string
	SyncMapSid string
}

func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		key:        properties.Key,
		serviceSid: properties.ServiceSid,
		syncMapSid: properties.SyncMapSid,
	}
}
