// This is an autogenerated file. DO NOT MODIFY
package execution

import (
	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/service/studio/v2/flow/execution/context"
	"github.com/RJPearson94/twilio-sdk-go/service/studio/v2/flow/execution/step"
)

type Client struct {
	client  *client.Client
	flowSid string
	sid     string
	Context func() *context.Client
	Step    func(string) *step.Client
}

func New(client *client.Client, flowSid string, sid string) *Client {
	return &Client{
		client:  client,
		flowSid: flowSid,
		sid:     sid,
		Context: func() *context.Client { return context.New(client, sid, flowSid) },
		Step:    func(stepSid string) *step.Client { return step.New(client, sid, flowSid, stepSid) },
	}
}
