// This is an autogenerated file. DO NOT MODIFY
package version

import (
	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/service/serverless/v1/service/function/version/content"
)

type Client struct {
	client *client.Client

	functionSid string
	serviceSid  string
	sid         string

	// Sub client to manage content resources
	Content *content.Client
}

// The properties required to manage the version resources
type ClientProperties struct {
	FunctionSid string
	ServiceSid  string
	Sid         string
}

// Create a new instance of the client
func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		functionSid: properties.FunctionSid,
		serviceSid:  properties.ServiceSid,
		sid:         properties.Sid,

		Content: content.New(client, content.ClientProperties{
			FunctionSid: properties.FunctionSid,
			ServiceSid:  properties.ServiceSid,
			VersionSid:  properties.Sid,
		}),
	}
}
