// This is an autogenerated file. DO NOT MODIFY
package invites

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type CreateChannelInviteInput struct {
	Identity string  `validate:"required" form:"Identity"`
	RoleSid  *string `form:"RoleSid,omitempty"`
}

type CreateChannelInviteResponse struct {
	AccountSid  string     `json:"account_sid"`
	ChannelSid  string     `json:"channel_sid"`
	CreatedBy   *string    `json:"created_by,omitempty"`
	DateCreated time.Time  `json:"date_created"`
	DateUpdated *time.Time `json:"date_updated,omitempty"`
	Identity    string     `json:"identity"`
	RoleSid     *string    `json:"role_sid,omitempty"`
	ServiceSid  string     `json:"service_sid"`
	Sid         string     `json:"sid"`
	URL         string     `json:"url"`
}

func (c Client) Create(input *CreateChannelInviteInput) (*CreateChannelInviteResponse, error) {
	return c.CreateWithContext(context.Background(), input)
}

func (c Client) CreateWithContext(context context.Context, input *CreateChannelInviteInput) (*CreateChannelInviteResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Services/{serviceSid}/Channels/{channelSid}/Invites",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"serviceSid": c.serviceSid,
			"channelSid": c.channelSid,
		},
	}

	response := &CreateChannelInviteResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
