// This is an autogenerated file. DO NOT MODIFY
package list

import (
	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/service/sync/v1/service/list/item"
	"github.com/RJPearson94/twilio-sdk-go/service/sync/v1/service/list/items"
	"github.com/RJPearson94/twilio-sdk-go/service/sync/v1/service/list/permissions"
)

type Client struct {
	client *client.Client

	serviceSid string
	sid        string

	Item        func(int) *item.Client
	Items       *items.Client
	Permissions func(string) *permissions.Client
}

type ClientProperties struct {
	ServiceSid string
	Sid        string
}

func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		serviceSid: properties.ServiceSid,
		sid:        properties.Sid,

		Item: func(index int) *item.Client {
			return item.New(client, item.ClientProperties{
				Index:      index,
				ListSid:    properties.Sid,
				ServiceSid: properties.ServiceSid,
			})
		},
		Items: items.New(client, items.ClientProperties{
			ListSid:    properties.Sid,
			ServiceSid: properties.ServiceSid,
		}),
		Permissions: func(identity string) *permissions.Client {
			return permissions.New(client, permissions.ClientProperties{
				Identity:   identity,
				ListSid:    properties.Sid,
				ServiceSid: properties.ServiceSid,
			})
		},
	}
}
