// This is an autogenerated file. DO NOT MODIFY
package workflow

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetTaskQueueResponse struct {
	AccountSid                    string      `json:"account_sid"`
	AssignmentCallbackURL         *string     `json:"assignment_callback_url,omitempty"`
	Configuration                 interface{} `json:"configuration"`
	DateCreated                   time.Time   `json:"date_created"`
	DateUpdated                   *time.Time  `json:"date_updated,omitempty"`
	DocumentContentType           string      `json:"document_content_type"`
	FallbackAssignmentCallbackURL *string     `json:"fallback_assignment_callback_url,omitempty"`
	FriendlyName                  string      `json:"friendly_name"`
	Sid                           string      `json:"sid"`
	TaskReservationTimeout        int         `json:"task_reservation_timeout"`
	URL                           string      `json:"url"`
	WorkspaceSid                  string      `json:"workspace_sid"`
}

func (c Client) Get() (*GetTaskQueueResponse, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetTaskQueueResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Workspaces/{workspaceSid}/Workflows/{sid}",
		PathParams: map[string]string{
			"workspaceSid": c.workspaceSid,
			"sid":          c.sid,
		},
	}

	response := &GetTaskQueueResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
