// This is an autogenerated file. DO NOT MODIFY
package balance

import (
	"context"
	"net/http"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

// FetchBalanceResponse resource/ response properties for retrieving an account balance
type FetchBalanceResponse struct {
	// The SID of account the balance was retrieved for
	AccountSid string `json:"account_sid"`
	// The currency format for the balance
	Balance string `json:"balance"`
	// The account currency format
	Currency string `json:"currency"`
}

// Fetch retrieves the balance resource for the account
// Context is defaulted to Background. See https://golang.org/pkg/context/#Background for more information
func (c Client) Fetch() (*FetchBalanceResponse, error) {
	return c.FetchWithContext(context.Background())
}

// FetchWithContext retrieves the balance resource for the account
func (c Client) FetchWithContext(context context.Context) (*FetchBalanceResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Accounts/{accountSid}/Balance.json",
		PathParams: map[string]string{
			"accountSid": c.accountSid,
		},
	}

	response := &FetchBalanceResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
