// This is an autogenerated file. DO NOT MODIFY
package webhook

import (
	"context"
	"net/http"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type UpdateWebhookInput struct {
	Filters        *[]string `form:"Filters,omitempty"`
	Method         *string   `form:"Method,omitempty"`
	PostWebhookUrl *string   `form:"PostWebhookUrl,omitempty"`
	PreWebhookUrl  *string   `form:"PreWebhookUrl,omitempty"`
	Target         *string   `form:"Target,omitempty"`
}

type UpdateWebhookResponse struct {
	AccountSid     string   `json:"account_sid"`
	Filters        []string `json:"filters"`
	Method         string   `json:"method"`
	PostWebhookUrl *string  `json:"post_webhook_url,omitempty"`
	PreWebhookUrl  *string  `json:"pre_webhook_url,omitempty"`
	Target         string   `json:"target"`
	URL            string   `json:"url"`
}

func (c Client) Update(input *UpdateWebhookInput) (*UpdateWebhookResponse, error) {
	return c.UpdateWithContext(context.Background(), input)
}

func (c Client) UpdateWithContext(context context.Context, input *UpdateWebhookInput) (*UpdateWebhookResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Conversations/Webhooks",
		ContentType: client.URLEncoded,
	}

	response := &UpdateWebhookResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
