// This is an autogenerated file. DO NOT MODIFY
package channel

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetChannelOutput struct {
	Sid           string     `json:"sid"`
	AccountSid    string     `json:"account_sid"`
	ServiceSid    string     `json:"service_sid"`
	FriendlyName  *string    `json:"friendly_name,omitempty"`
	UniqueName    *string    `json:"unique_name,omitempty"`
	Attributes    *string    `json:"attributes,omitempty"`
	Type          string     `json:"type"`
	CreatedBy     string     `json:"created_by"`
	MembersCount  int        `json:"members_count"`
	MessagesCount int        `json:"messages_count"`
	DateCreated   time.Time  `json:"date_created"`
	DateUpdated   *time.Time `json:"date_updated,omitempty"`
	URL           string     `json:"url"`
}

func (c Client) Get() (*GetChannelOutput, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetChannelOutput, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Services/{serviceSid}/Channels/{sid}",
		PathParams: map[string]string{
			"serviceSid": c.serviceSid,
			"sid":        c.sid,
		},
	}

	output := &GetChannelOutput{}
	if err := c.client.Send(context, op, nil, output); err != nil {
		return nil, err
	}
	return output, nil
}
