// This is an autogenerated file. DO NOT MODIFY
package channel

import "github.com/RJPearson94/twilio-sdk-go/client"

type Client struct {
	client     *client.Client
	serviceSid string
	sid        string
	userSid    string
}

func New(client *client.Client, serviceSid string, sid string, userSid string) *Client {
	return &Client{
		client:     client,
		serviceSid: serviceSid,
		sid:        sid,
		userSid:    userSid,
	}
}
