// This is an autogenerated file. DO NOT MODIFY
package samples

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type CreateSampleInput struct {
	Language      string  `validate:"required" form:"Language"`
	TaggedText    string  `validate:"required" form:"TaggedText"`
	SourceChannel *string `form:"SourceChannel,omitempty"`
}

type CreateSampleResponse struct {
	Sid           string     `json:"sid"`
	AccountSid    string     `json:"account_sid"`
	AssistantSid  string     `json:"assistant_sid"`
	TaskSid       string     `json:"task_sid"`
	Language      string     `json:"language"`
	TaggedText    string     `json:"tagged_text"`
	SourceChannel *string    `json:"source_channel,omitempty"`
	DateCreated   time.Time  `json:"date_created"`
	DateUpdated   *time.Time `json:"date_updated,omitempty"`
	URL           string     `json:"url"`
}

func (c Client) Create(input *CreateSampleInput) (*CreateSampleResponse, error) {
	return c.CreateWithContext(context.Background(), input)
}

func (c Client) CreateWithContext(context context.Context, input *CreateSampleInput) (*CreateSampleResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Assistants/{assistantSid}/Tasks/{taskSid}/Samples",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"assistantSid": c.assistantSid,
			"taskSid":      c.taskSid,
		},
	}

	response := &CreateSampleResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
