// This is an autogenerated file. DO NOT MODIFY
package samples

import "github.com/RJPearson94/twilio-sdk-go/client"

type Client struct {
	client *client.Client

	assistantSid string
	taskSid      string
}

// The properties required to manage the samples resources
type ClientProperties struct {
	AssistantSid string
	TaskSid      string
}

// Create a new instance of the client
func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		assistantSid: properties.AssistantSid,
		taskSid:      properties.TaskSid,
	}
}
