// This is an autogenerated file. DO NOT MODIFY
package asset

import (
	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/service/serverless/v1/service/asset/version"
	"github.com/RJPearson94/twilio-sdk-go/service/serverless/v1/service/asset/versions"
)

type Client struct {
	client *client.Client

	serviceSid string
	sid        string

	// Sub client to manage version resources
	Version func(string) *version.Client
	// Sub client to manage versions resources
	Versions *versions.Client
}

// The properties required to manage the asset resources
type ClientProperties struct {
	ServiceSid string
	Sid        string
}

// Create a new instance of the client
func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		serviceSid: properties.ServiceSid,
		sid:        properties.Sid,

		Version: func(versionSid string) *version.Client {
			return version.New(client, version.ClientProperties{
				AssetSid:   properties.Sid,
				ServiceSid: properties.ServiceSid,
				Sid:        versionSid,
			})
		},
		Versions: versions.New(client, versions.ClientProperties{
			AssetSid:   properties.Sid,
			ServiceSid: properties.ServiceSid,
		}),
	}
}
