// This is an autogenerated file. DO NOT MODIFY
package query

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetQueryResponseField struct {
	Name  string `json:"name"`
	Type  string `json:"type"`
	Value string `json:"value"`
}

type GetQueryResponseResult struct {
	Fields []GetQueryResponseField `json:"fields"`
	Task   string                  `json:"task"`
}

type GetQueryResponse struct {
	AccountSid    string                 `json:"account_sid"`
	AssistantSid  string                 `json:"assistant_sid"`
	DateCreated   time.Time              `json:"date_created"`
	DateUpdated   *time.Time             `json:"date_updated,omitempty"`
	DialogueSid   *string                `json:"dialogue_sid,omitempty"`
	Language      string                 `json:"language"`
	ModelBuildSid string                 `json:"model_build_sid"`
	Query         string                 `json:"query"`
	Results       GetQueryResponseResult `json:"results"`
	SampleSid     string                 `json:"sample_sid"`
	Sid           string                 `json:"sid"`
	SourceChannel string                 `json:"source_channel"`
	Status        string                 `json:"status"`
	URL           string                 `json:"url"`
}

func (c Client) Get() (*GetQueryResponse, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetQueryResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Assistants/{assistantSid}/Queries/{sid}",
		PathParams: map[string]string{
			"assistantSid": c.assistantSid,
			"sid":          c.sid,
		},
	}

	response := &GetQueryResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
