// This is an autogenerated file. DO NOT MODIFY
package task_channel

import "github.com/RJPearson94/twilio-sdk-go/client"

type Client struct {
	client *client.Client

	sid          string
	workspaceSid string
}

// The properties required to manage the task channel resources
type ClientProperties struct {
	Sid          string
	WorkspaceSid string
}

// Create a new instance of the client
func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		sid:          properties.Sid,
		workspaceSid: properties.WorkspaceSid,
	}
}
