// This is an autogenerated file. DO NOT MODIFY
package task_channel

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type UpdateTaskChannelInput struct {
	ChannelOptimizedRouting *bool   `form:"ChannelOptimizedRouting,omitempty"`
	FriendlyName            *string `form:"FriendlyName,omitempty"`
}

type UpdateTaskChannelResponse struct {
	AccountSid              string     `json:"account_sid"`
	ChannelOptimizedRouting *bool      `json:"channel_optimized_routing,omitempty"`
	DateCreated             time.Time  `json:"date_created"`
	DateUpdated             *time.Time `json:"date_updated,omitempty"`
	FriendlyName            string     `json:"friendly_name"`
	Sid                     string     `json:"sid"`
	URL                     string     `json:"url"`
	UniqueName              string     `json:"unique_name"`
	WorkspaceSid            string     `json:"workspace_sid"`
}

func (c Client) Update(input *UpdateTaskChannelInput) (*UpdateTaskChannelResponse, error) {
	return c.UpdateWithContext(context.Background(), input)
}

func (c Client) UpdateWithContext(context context.Context, input *UpdateTaskChannelInput) (*UpdateTaskChannelResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Workspaces/{workspaceSid}/TaskChannels/{sid}",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"workspaceSid": c.workspaceSid,
			"sid":          c.sid,
		},
	}

	response := &UpdateTaskChannelResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
