// This is an autogenerated file. DO NOT MODIFY
package accounts

import (
	"context"
	"net/http"

	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/utils"
)

type CreateAccountInput struct {
	FriendlyName *string `form:"FriendlyName,omitempty"`
	Status       *string `form:"Status,omitempty"`
}

type CreateAccountResponse struct {
	AuthToken       string             `json:"auth_token"`
	DateCreated     utils.RFC2822Time  `json:"date_created"`
	DateUpdated     *utils.RFC2822Time `json:"date_updated,omitempty"`
	FriendlyName    string             `json:"friendly_name"`
	OwnerAccountSid string             `json:"owner_account_sid"`
	Sid             string             `json:"sid"`
	Status          string             `json:"status"`
	Type            string             `json:"type"`
}

func (c Client) Create(input *CreateAccountInput) (*CreateAccountResponse, error) {
	return c.CreateWithContext(context.Background(), input)
}

func (c Client) CreateWithContext(context context.Context, input *CreateAccountInput) (*CreateAccountResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Accounts.json",
		ContentType: client.URLEncoded,
	}

	response := &CreateAccountResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
