// This is an autogenerated file. DO NOT MODIFY
package field

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetFieldResponse struct {
	Sid          string     `json:"sid"`
	AccountSid   string     `json:"account_sid"`
	AssistantSid string     `json:"assistant_sid"`
	TaskSid      string     `json:"task_sid"`
	UniqueName   string     `json:"unique_name"`
	FieldType    string     `json:"field_type"`
	DateCreated  time.Time  `json:"date_created"`
	DateUpdated  *time.Time `json:"date_updated,omitempty"`
	URL          string     `json:"url"`
}

func (c Client) Get() (*GetFieldResponse, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetFieldResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Assistants/{assistantSid}/Tasks/{taskSid}/Fields/{sid}",
		PathParams: map[string]string{
			"assistantSid": c.assistantSid,
			"taskSid":      c.taskSid,
			"sid":          c.sid,
		},
	}

	response := &GetFieldResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
