// This is an autogenerated file. DO NOT MODIFY
package media

import (
	"context"
	"net/http"

	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/utils"
)

type GetMediaResponse struct {
	AccountSid  string             `json:"account_sid"`
	ParentSid   string             `json:"parent_sid"`
	Sid         string             `json:"sid"`
	ContentType string             `json:"content_type"`
	DateCreated utils.RFC2822Time  `json:"date_created"`
	DateUpdated *utils.RFC2822Time `json:"date_updated,omitempty"`
}

func (c Client) Get() (*GetMediaResponse, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetMediaResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Accounts/{accountSid}/Messages/{messageSid}/Media/{sid}.json",
		PathParams: map[string]string{
			"accountSid": c.accountSid,
			"messageSid": c.messageSid,
			"sid":        c.sid,
		},
	}

	response := &GetMediaResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
