// This is an autogenerated file. DO NOT MODIFY
package webhooks

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type CreateConversationWebhookInput struct {
	Target                   string    `validate:"required" form:"target"`
	ConfigurationUrl         *string   `form:"Configuration.Url,omitempty"`
	ConfigurationMethod      *string   `form:"Configuration.Method,omitempty"`
	ConfigurationFilters     *[]string `form:"Configuration.Filters,omitempty"`
	ConfigurationTriggers    *[]string `form:"Configuration.Triggers,omitempty"`
	ConfigurationFlowSid     *string   `form:"Configuration.FlowSid,omitempty"`
	ConfigurationReplayAfter *int      `form:"Configuration.ReplayAfter,omitempty"`
}

type CreateConversationWebhookOutputConfiguration struct {
	Url         *string   `json:"url,omitempty"`
	Method      *string   `json:"method,omitempty"`
	Filters     *[]string `json:"filters,omitempty"`
	Triggers    *[]string `json:"triggers,omitempty"`
	FlowSid     *string   `json:"flow_sid,omitempty"`
	ReplayAfter *int      `json:"replay_after,omitempty"`
}

type CreateConversationWebhookOutput struct {
	Sid             string                                       `json:"sid"`
	AccountSid      string                                       `json:"account_sid"`
	ConversationSid string                                       `json:"conversation_sid"`
	Target          string                                       `json:"target"`
	Configuration   CreateConversationWebhookOutputConfiguration `json:"configuration"`
	DateCreated     time.Time                                    `json:"date_created"`
	DateUpdated     *time.Time                                   `json:"date_updated,omitempty"`
	URL             string                                       `json:"url"`
}

func (c Client) Create(input *CreateConversationWebhookInput) (*CreateConversationWebhookOutput, error) {
	return c.CreateWithContext(context.Background(), input)
}

func (c Client) CreateWithContext(context context.Context, input *CreateConversationWebhookInput) (*CreateConversationWebhookOutput, error) {
	op := client.Operation{
		HTTPMethod:  http.MethodPost,
		HTTPPath:    "/Conversations/{conversationSid}/Webhooks",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"conversationSid": c.conversationSid,
		},
	}

	output := &CreateConversationWebhookOutput{}
	if err := c.client.Send(context, op, input, output); err != nil {
		return nil, err
	}
	return output, nil
}
