// This is an autogenerated file. DO NOT MODIFY
package media_file

import (
	"context"
	"net/http"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

// Delete removes a media resource from the account
// See https://www.twilio.com/docs/fax/api/fax-media-resource#delete-a-fax-media-resource for more details
// Context is defaulted to Background. See https://golang.org/pkg/context/#Background for more information
func (c Client) Delete() error {
	return c.DeleteWithContext(context.Background())
}

// DeleteWithContext removes a media resource from the account
// See https://www.twilio.com/docs/fax/api/fax-media-resource#delete-a-fax-media-resource for more details
func (c Client) DeleteWithContext(context context.Context) error {
	op := client.Operation{
		Method: http.MethodDelete,
		URI:    "/Faxes/{faxSid}/Media/{sid}",
		PathParams: map[string]string{
			"faxSid": c.faxSid,
			"sid":    c.sid,
		},
	}

	if err := c.client.Send(context, op, nil, nil); err != nil {
		return err
	}
	return nil
}
