// This is an autogenerated file. DO NOT MODIFY
package task_queue

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetTaskQueueResponse struct {
	AccountSid              string     `json:"account_sid"`
	AssignmentActivityName  *string    `json:"assignment_activity_name,omitempty"`
	AssignmentActivitySid   *string    `json:"assignment_activity_sid,omitempty"`
	DateCreated             time.Time  `json:"date_created"`
	DateUpdated             *time.Time `json:"date_updated,omitempty"`
	EventCallbackURL        *string    `json:"event_callback_url,omitempty"`
	FriendlyName            string     `json:"friendly_name"`
	MaxReservedWorkers      int        `json:"max_reserved_workers"`
	ReservationActivityName *string    `json:"reservation_activity_name,omitempty"`
	ReservationActivitySid  *string    `json:"reservation_activity_sid,omitempty"`
	Sid                     string     `json:"sid"`
	TargetWorkers           *string    `json:"target_workers,omitempty"`
	TaskOrder               string     `json:"task_order"`
	URL                     string     `json:"url"`
	WorkspaceSid            string     `json:"workspace_sid"`
}

func (c Client) Get() (*GetTaskQueueResponse, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetTaskQueueResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Workspaces/{workspaceSid}/TaskQueues/{sid}",
		PathParams: map[string]string{
			"workspaceSid": c.workspaceSid,
			"sid":          c.sid,
		},
	}

	response := &GetTaskQueueResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
