// This is an autogenerated file. DO NOT MODIFY
package model_builds

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type CreateModelBuildInput struct {
	UniqueName     *string `form:"UniqueName,omitempty"`
	StatusCallback *string `form:"StatusCallback,omitempty"`
}

type CreateModelBuildResponse struct {
	Sid           string     `json:"sid"`
	AccountSid    string     `json:"account_sid"`
	AssistantSid  string     `json:"assistant_sid"`
	UniqueName    string     `json:"unique_name"`
	BuildDuration *int       `json:"build_duration,omitempty"`
	Status        string     `json:"status"`
	ErrorCode     *int       `json:"error_code,omitempty"`
	DateCreated   time.Time  `json:"date_created"`
	DateUpdated   *time.Time `json:"date_updated,omitempty"`
	URL           string     `json:"url"`
}

func (c Client) Create(input *CreateModelBuildInput) (*CreateModelBuildResponse, error) {
	return c.CreateWithContext(context.Background(), input)
}

func (c Client) CreateWithContext(context context.Context, input *CreateModelBuildInput) (*CreateModelBuildResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Assistants/{assistantSid}/ModelBuilds",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"assistantSid": c.assistantSid,
		},
	}

	response := &CreateModelBuildResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
