// This is an autogenerated file. DO NOT MODIFY
package executions

import "github.com/RJPearson94/twilio-sdk-go/client"

type Client struct {
	client *client.Client

	flowSid string
}

type ClientProperties struct {
	FlowSid string
}

func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		flowSid: properties.FlowSid,
	}
}
