// This is an autogenerated file. DO NOT MODIFY
package participant

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetParticipantOutput struct {
	Sid                string     `json:"sid"`
	AccountSid         string     `json:"account_sid"`
	ServiceSid         string     `json:"service_sid"`
	SessionSid         string     `json:"session_sid"`
	Identifier         string     `json:"identifier"`
	ProxyIdentifier    *string    `json:"proxy_identifier,omitempty"`
	ProxyIdentifierSid *string    `json:"proxy_identifier_sid,omitempty"`
	FriendlyName       *string    `json:"friendly_name,omitempty"`
	DateDeleted        *time.Time `json:"date_deleted,omitempty"`
	DateCreated        time.Time  `json:"date_created"`
	DateUpdated        *time.Time `json:"date_updated,omitempty"`
	URL                string     `json:"url"`
}

func (c Client) Get() (*GetParticipantOutput, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetParticipantOutput, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Services/{serviceSid}/Sessions/{sessionSid}/Participants/{sid}",
		PathParams: map[string]string{
			"serviceSid": c.serviceSid,
			"sessionSid": c.sessionSid,
			"sid":        c.sid,
		},
	}

	output := &GetParticipantOutput{}
	if err := c.client.Send(context, op, nil, output); err != nil {
		return nil, err
	}
	return output, nil
}
