// This is an autogenerated file. DO NOT MODIFY
package deployments

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type CreateDeploymentInput struct {
	BuildSid *string `form:"BuildSid,omitempty"`
}

type CreateDeploymentOutput struct {
	Sid            string     `json:"sid"`
	AccountSid     string     `json:"account_sid"`
	ServiceSid     string     `json:"service_sid"`
	EnvironmentSid string     `json:"environment_sid"`
	BuildSid       string     `json:"build_sid"`
	DateCreated    time.Time  `json:"date_created"`
	DateUpdated    *time.Time `json:"date_updated,omitempty"`
	URL            string     `json:"url"`
}

func (c Client) Create(input *CreateDeploymentInput) (*CreateDeploymentOutput, error) {
	return c.CreateWithContext(context.Background(), input)
}

func (c Client) CreateWithContext(context context.Context, input *CreateDeploymentInput) (*CreateDeploymentOutput, error) {
	op := client.Operation{
		HTTPMethod:  http.MethodPost,
		HTTPPath:    "/Services/{serviceSid}/Environments/{environmentSid}/Deployments",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"serviceSid":     c.serviceSid,
			"environmentSid": c.environmentSid,
		},
	}

	output := &CreateDeploymentOutput{}
	if err := c.client.Send(context, op, input, output); err != nil {
		return nil, err
	}
	return output, nil
}
