// This is an autogenerated file. DO NOT MODIFY
package phone_number

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetPhoneNumberResponseCapabilities struct {
	SmsInbound               *bool `json:"sms_inbound,omitempty"`
	SmsOutbound              *bool `json:"sms_outbound,omitempty"`
	RestrictionSmsDomestic   *bool `json:"restriction_sms_domestic,omitempty"`
	RestrictionVoiceDomestic *bool `json:"restriction_voice_domestic,omitempty"`
	VoiceOutbound            *bool `json:"voice_outbound,omitempty"`
	VoiceInbound             *bool `json:"voice_inbound,omitempty"`
	FaxInbound               *bool `json:"fax_inbound,omitempty"`
	FaxOutbound              *bool `json:"fax_outbound,omitempty"`
	RestrictionFaxDomestic   *bool `json:"restriction_fax_domestic,omitempty"`
	RestrictionMmsDomestic   *bool `json:"restriction_mms_domestic,omitempty"`
	MmsOutbound              *bool `json:"mms_outbound,omitempty"`
	MmsInbound               *bool `json:"mms_inbound,omitempty"`
	SipTrunking              *bool `json:"sip_trunking,omitempty"`
}

type GetPhoneNumberResponse struct {
	Sid          string                              `json:"sid"`
	AccountSid   string                              `json:"account_sid"`
	ServiceSid   string                              `json:"service_sid"`
	PhoneNumber  *string                             `json:"phone_number,omitempty"`
	FriendlyName *string                             `json:"friendly_name,omitempty"`
	IsoCountry   *string                             `json:"iso_country,omitempty"`
	Capabilities *GetPhoneNumberResponseCapabilities `json:"capabilities,omitempty"`
	IsReserved   *bool                               `json:"is_reserved,omitempty"`
	InUse        *int                                `json:"in_use,omitempty"`
	DateCreated  time.Time                           `json:"date_created"`
	DateUpdated  *time.Time                          `json:"date_updated,omitempty"`
	URL          string                              `json:"url"`
}

func (c Client) Get() (*GetPhoneNumberResponse, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetPhoneNumberResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Services/{serviceSid}/PhoneNumbers/{sid}",
		PathParams: map[string]string{
			"serviceSid": c.serviceSid,
			"sid":        c.sid,
		},
	}

	response := &GetPhoneNumberResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
