// This is an autogenerated file. DO NOT MODIFY
package workers

import "github.com/RJPearson94/twilio-sdk-go/client"

// Client for managing worker resources
// See https://www.twilio.com/docs/taskrouter/api/worker for more details
type Client struct {
	client *client.Client

	workspaceSid string
}

// ClientProperties are the properties required to manage the workers resources
type ClientProperties struct {
	WorkspaceSid string
}

// New creates a new instance of the workers client
func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		workspaceSid: properties.WorkspaceSid,
	}
}
