// This is an autogenerated file. DO NOT MODIFY
package feedback

import (
	"context"
	"net/http"

	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/utils"
)

type CreateFeedbackInput struct {
	Outcome *string `form:"Outcome,omitempty"`
}

type CreateFeedbackResponse struct {
	AccountSid  string             `json:"account_sid"`
	DateCreated utils.RFC2822Time  `json:"date_created"`
	DateUpdated *utils.RFC2822Time `json:"date_updated,omitempty"`
	MessageSid  string             `json:"message_sid"`
	Outcome     string             `json:"outcome"`
	Sid         string             `json:"sid"`
}

func (c Client) Create(input *CreateFeedbackInput) (*CreateFeedbackResponse, error) {
	return c.CreateWithContext(context.Background(), input)
}

func (c Client) CreateWithContext(context context.Context, input *CreateFeedbackInput) (*CreateFeedbackResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Accounts/{accountSid}/Messages/{messageSid}/Feedback.json",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"accountSid": c.accountSid,
			"messageSid": c.messageSid,
		},
	}

	response := &CreateFeedbackResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
