// This is an autogenerated file. DO NOT MODIFY
package message

import "github.com/RJPearson94/twilio-sdk-go/client"

type Client struct {
	client *client.Client

	conversationSid string
	sid             string
}

// The properties required to manage the message resources
type ClientProperties struct {
	ConversationSid string
	Sid             string
}

// Create a new instance of the client
func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		conversationSid: properties.ConversationSid,
		sid:             properties.Sid,
	}
}
