// This is an autogenerated file. DO NOT MODIFY
package message

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/utils"
)

type UpdateMessageInput struct {
	Attributes  *string            `form:"Attributes.Filters,omitempty"`
	Author      *string            `form:"Author,omitempty"`
	Body        *string            `form:"Body,omitempty"`
	DateCreated *utils.RFC2822Time `form:"DateCreated,omitempty"`
	DateUpdated *utils.RFC2822Time `form:"DateUpdated,omitempty"`
}

type UpdateMessageResponseMedia struct {
	ContentType string `json:"content_type"`
	Filename    string `json:"filename"`
	Sid         string `json:"sid"`
	Size        int    `json:"size"`
}

type UpdateMessageResponse struct {
	AccountSid      string                        `json:"account_sid"`
	Attributes      string                        `json:"attributes"`
	Author          string                        `json:"author"`
	Body            *string                       `json:"body,omitempty"`
	ConversationSid string                        `json:"conversation_sid"`
	DateCreated     time.Time                     `json:"date_created"`
	DateUpdated     *time.Time                    `json:"date_updated,omitempty"`
	Index           int                           `json:"index"`
	Media           *[]UpdateMessageResponseMedia `json:"media,omitempty"`
	ParticipantSid  *string                       `json:"participant_sid,omitempty"`
	Sid             string                        `json:"sid"`
	URL             string                        `json:"url"`
}

func (c Client) Update(input *UpdateMessageInput) (*UpdateMessageResponse, error) {
	return c.UpdateWithContext(context.Background(), input)
}

func (c Client) UpdateWithContext(context context.Context, input *UpdateMessageInput) (*UpdateMessageResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Conversations/{conversationSid}/Messages/{sid}",
		ContentType: client.URLEncoded,
		PathParams: map[string]string{
			"conversationSid": c.conversationSid,
			"sid":             c.sid,
		},
	}

	response := &UpdateMessageResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
