// This is an autogenerated file. DO NOT MODIFY
package binding

import "github.com/RJPearson94/twilio-sdk-go/client"

type Client struct {
	client *client.Client

	serviceSid string
	sid        string
	userSid    string
}

type ClientProperties struct {
	ServiceSid string
	Sid        string
	UserSid    string
}

func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		serviceSid: properties.ServiceSid,
		sid:        properties.Sid,
		userSid:    properties.UserSid,
	}
}
