// This is an autogenerated file. DO NOT MODIFY
package user

import (
	"github.com/RJPearson94/twilio-sdk-go/client"
	"github.com/RJPearson94/twilio-sdk-go/service/chat/v2/service/user/binding"
)

type Client struct {
	client     *client.Client
	serviceSid string
	sid        string
	Binding    func(string) *binding.Client
}

func New(client *client.Client, serviceSid string, sid string) *Client {
	return &Client{
		client:     client,
		serviceSid: serviceSid,
		sid:        sid,
		Binding:    func(bindingSid string) *binding.Client { return binding.New(client, serviceSid, bindingSid, sid) },
	}
}
