// This is an autogenerated file. DO NOT MODIFY
package defaults

import (
	"context"
	"net/http"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetDefaultResponse struct {
	AccountSid   string      `json:"account_sid"`
	AssistantSid string      `json:"assistant_sid"`
	Data         interface{} `json:"data"`
	URL          string      `json:"url"`
}

func (c Client) Get() (*GetDefaultResponse, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetDefaultResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Assistants/{assistantSid}/Defaults",
		PathParams: map[string]string{
			"assistantSid": c.assistantSid,
		},
	}

	response := &GetDefaultResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
