// This is an autogenerated file. DO NOT MODIFY
package version

import "github.com/RJPearson94/twilio-sdk-go/client"

type Client struct {
	client *client.Client

	assetSid   string
	serviceSid string
	sid        string
}

type ClientProperties struct {
	AssetSid   string
	ServiceSid string
	Sid        string
}

func New(client *client.Client, properties ClientProperties) *Client {
	return &Client{
		client: client,

		assetSid:   properties.AssetSid,
		serviceSid: properties.ServiceSid,
		sid:        properties.Sid,
	}
}
