// This is an autogenerated file. DO NOT MODIFY
package credentials

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type CreateCredentialInput struct {
	Type         string  `validate:"required" form:"Type"`
	FriendlyName *string `form:"FriendlyName,omitempty"`
	Certificate  *string `form:"Certificate,omitempty"`
	PrivateKey   *string `form:"PrivateKey,omitempty"`
	Sandbox      *bool   `form:"Sandbox,omitempty"`
	ApiKey       *string `form:"ApiKey,omitempty"`
	Secret       *string `form:"Secret,omitempty"`
}

type CreateCredentialResponse struct {
	Sid          string     `json:"sid"`
	AccountSid   string     `json:"account_sid"`
	FriendlyName *string    `json:"friendly_name,omitempty"`
	Type         string     `json:"type"`
	Sandbox      *string    `json:"sandbox,omitempty"`
	DateCreated  time.Time  `json:"date_created"`
	DateUpdated  *time.Time `json:"date_updated,omitempty"`
	URL          string     `json:"url"`
}

func (c Client) Create(input *CreateCredentialInput) (*CreateCredentialResponse, error) {
	return c.CreateWithContext(context.Background(), input)
}

func (c Client) CreateWithContext(context context.Context, input *CreateCredentialInput) (*CreateCredentialResponse, error) {
	op := client.Operation{
		Method:      http.MethodPost,
		URI:         "/Credentials",
		ContentType: client.URLEncoded,
	}

	response := &CreateCredentialResponse{}
	if err := c.client.Send(context, op, input, response); err != nil {
		return nil, err
	}
	return response, nil
}
