// This is an autogenerated file. DO NOT MODIFY
package participant

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetParticipantResponseMessageBinding struct {
	Address          string  `json:"address"`
	ProjectedAddress *string `json:"projected_address,omitempty"`
	ProxyAddress     string  `json:"proxy_address"`
	Type             string  `json:"type"`
}

type GetParticipantResponse struct {
	AccountSid       string                                `json:"account_sid"`
	Attributes       string                                `json:"attributes"`
	ConversationSid  string                                `json:"conversation_sid"`
	DateCreated      time.Time                             `json:"date_created"`
	DateUpdated      *time.Time                            `json:"date_updated,omitempty"`
	Identity         *string                               `json:"identity,omitempty"`
	MessagingBinding *GetParticipantResponseMessageBinding `json:"messaging_binding,omitempty"`
	RoleSid          *string                               `json:"role_sid,omitempty"`
	Sid              string                                `json:"sid"`
	URL              string                                `json:"url"`
}

func (c Client) Get() (*GetParticipantResponse, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetParticipantResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Conversations/{conversationSid}/Participants/{sid}",
		PathParams: map[string]string{
			"conversationSid": c.conversationSid,
			"sid":             c.sid,
		},
	}

	response := &GetParticipantResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
