// This is an autogenerated file. DO NOT MODIFY
package conversation

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type GetConversationOutputTimers struct {
	DateInactive *time.Time `json:"date_inactive,omitempty"`
	DateClosed   *time.Time `json:"date_closed,omitempty"`
}

type GetConversationOutput struct {
	Sid                 string                      `json:"sid"`
	AccountSid          string                      `json:"account_sid"`
	ChatServiceSid      *string                     `json:"chat_service_sid,omitempty"`
	MessagingServiceSid *string                     `json:"messaging_service_sid,omitempty"`
	FriendlyName        *string                     `json:"friendly_name,omitempty"`
	Attributes          string                      `json:"attributes"`
	State               string                      `json:"state"`
	Timers              GetConversationOutputTimers `json:"timers"`
	DateCreated         time.Time                   `json:"date_created"`
	DateUpdated         *time.Time                  `json:"date_updated,omitempty"`
	URL                 string                      `json:"url"`
}

func (c Client) Get() (*GetConversationOutput, error) {
	return c.GetWithContext(context.Background())
}

func (c Client) GetWithContext(context context.Context) (*GetConversationOutput, error) {
	op := client.Operation{
		HTTPMethod: http.MethodGet,
		HTTPPath:   "/Conversations/{sid}",
		PathParams: map[string]string{
			"sid": c.sid,
		},
	}

	output := &GetConversationOutput{}
	if err := c.client.Send(context, op, nil, output); err != nil {
		return nil, err
	}
	return output, nil
}
