// This is an autogenerated file. DO NOT MODIFY
package conversation

import (
	"context"
	"net/http"
	"time"

	"github.com/RJPearson94/twilio-sdk-go/client"
)

type FetchConversationResponseTimers struct {
	DateClosed   *time.Time `json:"date_closed,omitempty"`
	DateInactive *time.Time `json:"date_inactive,omitempty"`
}

type FetchConversationResponse struct {
	AccountSid          string                          `json:"account_sid"`
	Attributes          string                          `json:"attributes"`
	ChatServiceSid      *string                         `json:"chat_service_sid,omitempty"`
	DateCreated         time.Time                       `json:"date_created"`
	DateUpdated         *time.Time                      `json:"date_updated,omitempty"`
	FriendlyName        *string                         `json:"friendly_name,omitempty"`
	MessagingServiceSid *string                         `json:"messaging_service_sid,omitempty"`
	Sid                 string                          `json:"sid"`
	State               string                          `json:"state"`
	Timers              FetchConversationResponseTimers `json:"timers"`
	URL                 string                          `json:"url"`
}

func (c Client) Fetch() (*FetchConversationResponse, error) {
	return c.FetchWithContext(context.Background())
}

func (c Client) FetchWithContext(context context.Context) (*FetchConversationResponse, error) {
	op := client.Operation{
		Method: http.MethodGet,
		URI:    "/Conversations/{sid}",
		PathParams: map[string]string{
			"sid": c.sid,
		},
	}

	response := &FetchConversationResponse{}
	if err := c.client.Send(context, op, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}
